#!/bin/sh

# appearance
xrdb $XDG_CONFIG_HOME/X11/xresources &
xwallpaper --zoom $XDG_CONFIG_HOME/wall.* &
xset +fp $XDG_DATA_HOME/fonts/ &
xbanish -t 4000 &
xset dpms 0 0 0 &
xset -dpms &
xset s 3600 300 &
xss-lock -n $HOME/.local/bin/dim-screen.sh -- systemctl suspend-then-hibernate &
redshift &

# keyboard, disable touchpad while typing, and sound
setxkbmap -model pc105 -layout de,us -variant qwerty, -option grp:alt_shift_toggle -option caps:swapescape -option terminate:ctrl_alt_bksp &
syndaemon -K -i 0.5 -R -d &
xset -b &

# update environments
export BROWSER=qutebrowser
export COLORTERM=24bit

# window manager
exec i3
